// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package za.co.trf.recurly.sample.domain;

import org.springframework.beans.factory.annotation.Configurable;
import za.co.trf.recurly.sample.domain.Customer;

privileged aspect Customer_Roo_Configurable {
    
    declare @type: Customer: @Configurable;
    
}
